### ISSUE TITLE
scrolloff issue

### ISSUE THREAD

**Issue by viyic** [RMichelsen/Nvy#44] opened 2022-02-05 02:57 UTC
commands that add a new line (like 'p' and 'o') right before scrolloff line can cause display issue.
before 'o':
![05 09 45 29 Nvy](https://user-images.githubusercontent.com/13359085/152626078-2c98f256-92b7-4801-b895-ea44840630aa.png)
after 'o':
![05 09 45 43 Nvy](https://user-images.githubusercontent.com/13359085/152626083-99c43fde-4253-44a6-950e-53ec65cc7531.png)
this doesn't seem to happen in nvim-qt.

**Comment by EtiamNullam** [comment] 2022-04-27 22:54
Can't really see what is the display issue here. Maybe you can make a video of it?

**Comment by viyic** [comment] 2022-04-27 23:19
sure, this is me pressing 'o' a few times with scrolloff set to 3
![Nvy](https://user-images.githubusercontent.com/13359085/165646670-cce260cc-7d20-41f0-824a-66d48bee13c4.gif)

**Comment by EtiamNullam** [comment] 2022-04-27 23:50
Sorry, I really still can't see what is the problem. Do you mean its going down once? Are you sure its not the same in different neovim clients and with no config?

**Comment by viyic** [comment] 2022-04-28 00:28
the problem in that gif is `set linebreak` "copies" itself and overwrites `set showbreak` and `set breakindent`, which presumably comes from Nvy not refreshing/re-rendering the lines when creating a new line with `scrolloff` enabled.
i have tried it in nvim-qt and it works just fine.

it still happens in Nvy even with no config (pay attention to `set showbreak` and `set breakindent`).
![Nvy](https://user-images.githubusercontent.com/13359085/165651562-9e42f9ae-0a34-4267-8892-e0637c5b670d.gif)

**Comment by EtiamNullam** [comment] 2022-04-28 00:41
Oh, yeah sorry I did not know what kind of display issue I'm looking for :P

Well it seems fine for me. Any idea what I might be missing to reproduce it?

EDIT: actually its pretty obvious - it happens only with `:nonumber` set.

EDIT2: also it won't happen if you disable statusline with `:laststatus=0`

**Comment by RMichelsen** [comment] 2023-04-26 09:23
I think this may be fixed in #73 as I can't reproduce the issue - can you confirm that this is the case?

**Comment by viyic** [comment] 2023-04-26 11:09
it still happens sadly.

![image](https://user-images.githubusercontent.com/13359085/234549704-7b43f476-f30e-46d6-b8ca-e7d1d085f790.png)

i think the way to reproduce this is to `:set nonumber`, `:set norelativenumber`, `:set laststatus=2`, `:set scrolloff=3`, and try inserting new lines with `o` exactly above the scrolloff area without moving, so basically `o<ESC>o<ESC>`.

**Comment by RMichelsen** [comment] 2023-04-26 14:15
I'm trying to debug it but I am confused, I still can't figure out what's wrong. Initial guess was the right lines aren't being copied in [renderer.cpp:ScrollRegion()](https://github.com/RMichelsen/Nvy/blob/master/src/renderer/renderer.cpp#L867) but it seems to move the view down by one which seems correct so I don't think that's it. Why the lines aren't being updated with the proper content afterwards I do not understand. I'll try to find time to investigate more, in the mean time we could try to hotfix the issue by forcing a resize when inserting new lines, ugly but it would probably work.

**Comment by Zorbn** [comment] 2023-04-28 16:18
I also tried to debug this but I wasn't able to find a problem with `ScrollRegion` either. At first I thought the bottom few lines just weren't being updated but they stay broken even if you continue editing and scrolling afterward. It's really strange... I'm not sure what other GUIs are doing differently in this case.

**Comment by Zorbn** [comment] 2023-07-06 03:30
I've come back to this issue, and it seems that I found the bug. @viyic if you get the chance, please let me know if #90 fixes this for you. @RMichelsen it turns out `ScrollRegion` was only processing the first scroll event sent to it. The logic for shifting lines was correct, like you said.

**Comment by viyic** [comment] 2023-07-07 13:14
Yep, works great, thanks!

**Closed as completed** 2023-07-18 20:37 UTC
