### ISSUE TITLE
Powerline font not displaying correctly

### ISSUE THREAD

**Issue by Hyvok** [RMichelsen/Nvy#11] opened 2020-10-13 05:46 UTC
Nvy does not seem to display Powerline fonts correctly. Here is a screenshot showing Nvy at the top and nvim-qt under with the same nvim configuration using the font "Inconsolate for Powerline" from https://github.com/powerline/fonts/tree/master/Inconsolata The special symbols are not displaying correctly in the status bar.
<img width="727" alt="nvy_fonts" src="https://user-images.githubusercontent.com/1629028/95820183-50325800-0d30-11eb-8c99-e88f6d8bf174.PNG">

**Comment by RMichelsen** [comment] 2020-10-13 07:17
Can you try without the `:w57` at the end? Nvy does not support specifying weights this way

**Comment by Hyvok** [comment] 2020-10-13 07:43
Does not seem to make a difference. The full init.vim line for setting the font is `set guifont=Inconsolata\ for\ Powerline:h14`

**Comment by cpkio** [comment] 2020-10-13 08:23
@Hyvok Install Babelmap for example and show how it looks like there. I've experienced a similiar problem with JuliaMono releases, where \uE0A0 (branch symbol) is shifted way down on display but looks fine in other font viewing programs. It means the font was patched incorrectly.

**Comment by Hyvok** [comment] 2020-10-13 08:38
I think these are the symbols in question
<img width="563" alt="inconsolate_babelmap" src="https://user-images.githubusercontent.com/1629028/95836914-ab704480-0d48-11eb-81b0-e059d9541836.PNG">

**Comment by cpkio** [comment] 2020-10-13 09:00
Replacing my old comment — I see similar behaviour, but I think this is more of a font (char metadata) issue. Left-pointing triangle is misplaced in this font. Probably expecting from this cleartyped GDI Nvim frontend totally same behaviour isnt right

## Inconsolata for Powerline
![2020-10-13_115452](https://user-images.githubusercontent.com/1917113/95839001-23d80500-0d4b-11eb-84e2-532405b8479c.png)

## JuliaMono
![2020-10-13_115524](https://user-images.githubusercontent.com/1917113/95839006-263a5f00-0d4b-11eb-9d05-9d1a2420584f.png)

**Comment by RMichelsen** [comment] 2020-10-13 13:07
I believe different font shapers/renderers shape the fonts slightly differently and thats why the powerline fonts sometimes look a bit off. For a fair comparison to Nvy, you can try gvim with DirectWrite (`set renderoptions=type:directx`) or the [Windows Terminal](https://github.com/microsoft/terminal) which also uses DirectWrite. I am not sure I can do much to fix this on my end.

**Comment by Hyvok** [comment] 2020-10-14 11:38
Don't see any difference in rendering with gVim with `set renderoptions=type:directx`, the font seems to render fine.

**Comment by VladimirMarkelov** [comment] 2020-10-22 05:29
Today I discovered that fonts with powerline symbols can cause troubles even if no powerline symbol is displayed in the screen. For some reason regular Latin characters under cursor displayed distorted. Unfortunately, I did not have at hand an utility to capture a video, so I made two screenshots: in the first picture, the cursor is on `w`, in the next picture I pressed right arrow. All the text except under cursor is drawn without any glitches:

![nvy-001](https://user-images.githubusercontent.com/1577186/96828558-ba13c700-13ec-11eb-85c2-1c2f4ca9280d.png)

`->` pressed

![nvy-002](https://user-images.githubusercontent.com/1577186/96828591-c730b600-13ec-11eb-8b3d-e323b9913733.png)

It worked this way for both "Iosevka NF" and "Cascadia Mono PL". When I switched to "Iosevka Fixed" that does not have any powerline characters, graphic glitches disappeared.

**Comment by cpkio** [comment] 2020-10-22 08:03
I use Cascadia Mono PL daily with latest Nvy and have never seen any such glitches. Maybe the video driver is to blame? You should post Cascadia font version also.

**Comment by RMichelsen** [comment] 2020-10-22 09:56
@VladimirMarkelov I think this bug is unrelated to the powerline font issue, however I still want to fix it. Do you have some file or output I can open to reproduce the issue?

**Comment by VladimirMarkelov** [comment] 2020-10-22 16:58
Yes, old fonts it was the first thing I thought about. As of Cascadia Code, it was `2005.*` version and after updating to latest `2009.*`, the trouble is gone. `Iosevka NF` is quite old font as well(version 1.8.x - while the latest Iosevka is 3.x) downloaded some time ago from nerdfonts.com. They rarely update NF fonts, so eventually I dropped using their fonts in favor of original ones without any powerline characters. In other words, I fixed the using by using newer fonts, but I just wanted to add some more info about displaying patched fonts.

**Comment by RMichelsen** [comment] 2020-10-22 17:14
Hmm that is interesting, it makes me wonder whether some of the powerline fonts have a bug with some characters not being monospaced. Although if it only happens in Nvy it likely is an actual bug.

**Comment by VladimirMarkelov** [comment] 2020-10-22 17:46
And it is strange that only characters under cursor are displayed incorrectly. Reading the text in `nvy` with any of mentioned fonts is OK - no troubles, until you start moving the text cursor. I am not sure how to debug it and if it is worth it. Feel free to just add some info to FAQ and close the issue :) As for me, I do not like using NF/PL fonts any longer as those characters are not standard Unicode ones - one can expect anything from them.

**Comment by RMichelsen** [comment] 2020-10-22 17:51
It is because the cursor is drawn separately along with the character that it currently highlights. However it must be something to do with the unicode chars being incorrectly marked as double or single width, which is either a problem with the fonts or a problem with Nvy. Or maybe both haha :)

**Comment by VladimirMarkelov** [comment] 2020-10-22 18:49
I remember, when I used another `*-NF` font in gVim that had some of characters wider, gVim used maximal width to draw all the text, so it was displayed with big gaps between characters - it looked ugly.

By the way, I set the same "Iosevka NF" for gVim, and opened the same log file (with and without `set renderoptions=type:directx`) and it looked OK - no display glitches.

**Comment by RMichelsen** [comment] 2020-10-22 18:51
Could you send over the log file (or anything that reproduces this) and I'll try to download the font and reproduce, that way I might be able to figure out whats wrong even if its not that important it still seems like a bug in Nvy then.

**Comment by VladimirMarkelov** [comment] 2020-10-22 19:13
Here it is: I extracted two lines from the log, it is enough - I see the distortion even when open this tiny log.

[log_excerpt.log](https://github.com/RMichelsen/Nvy/files/5425157/log_excerpt.log)

Extra info:

- Windows 10 is Enterprise edition, and it is a bit old : 1809
- Scaling(though, I do not think it is important): 175%
- settings in `init.vim`: `set guifont=Iosevka\ NF:h12`
- Font downloaded from nerdfonts is quite old:
   * file name(I installed only one of the iosevka NF pack): iosevka nerd font complete mono windows compatible.ttf
   * font version: 1.8.4; ttfautohint(v1.5)
   * font issue date, it seems an old one: Copyright © 2015-2016

**Comment by RMichelsen** [comment] 2020-10-24 11:29
Wow this is odd, I cant reproduce with the same font and file.
![image](https://user-images.githubusercontent.com/42123601/97080596-cf5f4000-15fc-11eb-8405-7b147f1a5333.png)
![image](https://user-images.githubusercontent.com/42123601/97080622-033a6580-15fd-11eb-896c-2b1c26c687db.png)

**Comment by VladimirMarkelov** [comment] 2020-10-24 16:51
Maybe it is old Windows + Intel video card. It is a work laptop and I cannot do much on it (e.g, I cannot install new drivers and alike). Let's think, it is a my work laptop trouble only :)

**Comment by RMichelsen** [comment] 2020-10-25 12:12
Hmm yea, well I'll close the issue for now then. If anyone finds a way for me to reproduce this behavior I'll look into whether its a bug in Nvy.

**Closed as completed by RMichelsen** 2020-10-25 12:12 UTC
