### ISSUE TITLE
Black area at bottom of window

### ISSUE THREAD

**Issue by sid-6581** [RMichelsen/Nvy#63] opened 2022-10-31 16:53 UTC
I'm on a 4k screen using PowerToys FancyZones to resize nvy on startup, and if nvy takes the full height of the screen there is a large black portion at the bottom. This isn't a problem if I start nvy with a smaller size. Trying to force a redraw doesn't work, and loading a file that needs the entire screen height to render doesn't work either. Resizing the window fixes it.

It looks like the surface allocated just isn't tall enough, but when it's reallocated it works fine.

![image](https://user-images.githubusercontent.com/28602336/199063576-89a0f30f-6074-4b88-a783-5ec9d317377c.png)

**Comment by n0bra1n3r** [comment] 2023-04-13 21:56
This also happens to me when opening it up maximized from a shortcut on a 3k screen.

![image](https://user-images.githubusercontent.com/48817555/231891348-8f113cbf-77fb-4079-9240-1ed1796ffe17.png)

![image](https://user-images.githubusercontent.com/48817555/231891581-c5e007f3-ee9a-4432-a9af-73776ee2f90a.png)

**Comment by mvarelaf** [comment] 2023-04-16 16:08
I can also reproduce the issue with version 0.3.3 like [n0bra1n3r](https://github.com/n0bra1n3r) does, but using target `Nvy.exe --disable-ligatures +"terminal"`

When https://github.com/RMichelsen/Nvy/pull/76 gets merged I think this will be solved

**Comment by RMichelsen** [comment] 2023-04-26 09:54
#76 is now merged, can you confirm that this is fixed? I cannot reproduce.

**Comment by sid-6581** [comment] 2023-05-19 19:43
That fixes it for me!

**Closed as completed** 2023-05-19 19:50 UTC
